name: live_location_tracker
description: Real-time location tracking app with Firebase backend

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Location services
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  
  # Maps
  google_maps_flutter: ^2.5.0
  
  # Background services
  flutter_background_service: ^5.0.5
  
  # Permissions
  permission_handler: ^11.1.0
  
  # Storage
  shared_preferences: ^2.2.2
  
  # UI
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true